### ISSUE TITLE
Bug in the search box function

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#121]
The search box on http://www.als.scot/ is faulty.
Type in Andrena ruf, and you are offered two options (ruficrus and rufitarsis). Click on one of these, and instead of the name appearing in the search box the box clears

**Comment by RachelStroud** [comment]
I tried searching for Cladonia from the species search box. First I tried Clad which gave two sites, so then I tried  Cladonia which produced 105 species in random order (why not alphabetical?). 
I downloaded the list which gave me 409 species/varieties/aggregates each with a different taxon id.
Some species had multiple entries each witha different taxon id, but no other information - authorities not given.
There was no consistency in differentiating between species/ subspecies/variety/ aggregrate e.g. in the list
Next I tried Cladonia cri - which produced the same 105 Cladonia species.  
Next I tried Cladonia crispata, this produced 110 species, some of which were not Cladonia but carried the specific name crispata. I could then filter this to lichens and then had just 61 choices.  
OK so lichens might be taxonomically difficult so I tried  Lycopus euro this produced the correct species link  Lycopus europaeus but also 3 localities for Council of Europe Boulevard and 1 for Europe Road.  
Another example of this potential bug 

"I tried searching for Cladonia from the species search box. First I tried Clad which gave two sites, so then I tried  Cladonia which produced 105 species in random order, rather than alphabetical. 

Downloading the list which gave me 409 species/varieties/aggregates each with a different taxon id.
Some species had multiple entries each with a different taxon id, but no other information - authorities not given.

There was no consistency in differentiating between species/ subspecies/variety/ aggregrate e.g. in the list

Next I tried Cladonia cri - which produced the same 105 Cladonia species.  
Next I tried Cladonia crispata, this produced 110 species, some of which were not Cladonia but carried the specific name crispata. I could then filter this to lichens and then had just 61 choices.

**Comment by djtfmartin** [comment]
I think this issue needs some refinement. The only thing i see is support for partial matches like "Cladonia cri" which is a good requirement.

The results with search with "Cladonia" are expected. Top match is the genus. Users can filter to species using the facets on the left hand side.

Note theres a separate (bug) issue for sorting here #123

**Comment by djtfmartin** [comment]
I think this is fixed.

The main critical issue that @CEJohnston pointed out was the faulty autocomplete in the banner. This is now working.

Some of the points around Cladonia should probably be moved to a separate issue is they are required enhancements. I suspect the fixed autocomplete with fix most of the confusion above.

**Comment by RachelStroud** [comment]
Thanks @EllaVogel  will set up separate issue for you.
