### ISSUE TITLE
Redesign layout of dataset metadata pages

### ISSUE THREAD

**Issue by RachelStroud** [nbnuk/nbnatlas-issues#144]
Redesign dataset metadata page into 'tabular' form to reduce the amount of text on each page (see NBN Gateway layout)

https://data.nbn.org.uk/Datasets/GA000499

**Comment by djtfmartin** [comment]
Can i disagree with this one ? I dont think those pages look very good, so wonder why we would try to emulate.

We have a design for data partner pages which i think should feed in to the dataset display.

**Comment by EllaVogel** [comment]
I agree that the existing Gateway pages don't look great, but we'd like to
have the text collapsible in some way so that the page is less cluttered
and with less text.

Do you have sight of the new data partner pages and how they might affect
the dataset pages? Are we waiting for the Bootstrap upgrade before we can
roll this out?

**Comment by EllaVogel** [comment]
#33

**Comment by sophiathirza** [comment]
@EllaVogel is this still outstanding?

**Comment by sophiathirza** [comment]
#546

**Comment by c-van-dierkson** [comment]
Jo confirms to close.
