### ISSUE TITLE
Record coordinate uncertainty not aligning with coordinate precision

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#229]
Comment from DGERC on Forum thread [https://forums.nbn.org.uk/viewtopic.php?id=6817](url)

Browsing this I found that one record that we supplied to the NBN gateway had public visibility set at 10km square resolution (NY36) - during migration this now appears to (incorrectly) have a co-ordinate uncertainty of 1000 metres - see here [https://records.nbnatlas.org/occurrences/328586d8-9d85-4fab-9fcb-8eca08dfa998 ](url) Rest of the records in that dataset show co-ordinate uncertainty at 10000m correctly. Very odd!

Note from CJ - this record is the only sensitive species record in the set and is screened to the English list. Is this indicating a bug?

**Comment by sophiathirza** [comment]
@EllaVogel can you help me with this issue, please? The sensitive record was already supplied at a low resolution but then it looks like an additional uncertainty has been added. Is that correct?

**Comment by sophiathirza** [comment]
@EllaVogel this is the issue I mentioned at the meeting - where an additional uncertainty has been added to a sensitive species record which was already at a low resolution

**Comment by sophiathirza** [comment]
Sensitive records where the supplied resolution is the same or less than the required level of generalisation should not be generalised further.

It looks like, where this happens the supplied resolution is put in the coordinate precision field and the level of generalisation is put in the coordinate uncertainty in meters field.

Examples:
https://records.nbnatlas.org/occurrences/328586d8-9d85-4fab-9fcb-8eca08dfa998
https://records-dev.nbnatlas.org/occurrences/ef759faf-4c00-4380-b25d-8a608fe11345

I am sure that I have seen in on some sensitive records in the 'Coordinates generalised' field text that says something like: 'due to the level of generalistion the coordinates were not generalised further'.. i.e. the resolution is low enough already. If I can find an example I'll post it here

**Comment by sophiathirza** [comment]
Here is an example a record that was supplied at low enough resolution and no generalisation was applied: https://records.nbnatlas.org/occurrences/1bd1c2ab-5a3d-440a-a44c-22a90fcfd2c3

Text is: 'Location in Scotland is already generalised to 1.0 degrees. Sensitive in SCOTLAND, Name: Scotland, Zone: COUNTRY [Sensitive, Scottish Natural Heritage]'

**Comment by reupost** [comment]
But that record shows non-integer latitude and longitude values, surely it should have been generalised?

**Comment by sophiathirza** [comment]
Not if the supplied grid reference was at 100km already (i.e. NO). The lat long would have been derived from the centre of the 100km GR... should the coordinates not have decimal places?

**Comment by reupost** [comment]
As far as I can tell the record was provided at 10km resolution. This is what was packed into the 'original sensitive values' . As for the coordinates, you're right, they could be non-integer, though in this case they have been left unchanged from what was provided. Which was oddly also not a centroid of the relevant 10km grid square, but I think this might be due to the data provider simply truncating the values at [x=1] decimal places instead of calculating an actual centroid value for the grid square in which the record was made.

**Comment by sophiathirza** [comment]
okay, then I wonder why the note says: Location in Scotland is already generalised to 1.0 degrees.

**Comment by reupost** [comment]
Fixed

**Comment by sophiathirza** [comment]
This record: https://records-dev.nbnatlas.org/occurrences/ef759faf-4c00-4380-b25d-8a608fe11345 has an error that the coordinate uncertainty and precision have been transposed. I think it's because it's an original record that was transferred from the gateway and the precision field was used as the coordinate uncertainty. We don't have this error in new or updated records. So I will close the issue.
