### ISSUE TITLE
Spatial layer metadata updates using metadata form

### ISSUE THREAD

**Issue by CEJohnston** [nbnuk/nbnatlas-issues#309]
I added the word 'Natural' to the Description of layer 'AONB' - taking it from 'Areas of Outstanding Beauty (England)' to 'Areas of Outstanding Natural Beauty (England)'.  I can see the Description HAS changed in the metadata screen in the spatial portal OK (so that is working).  But the 'name' of the layer in the Add Layer screen still says 'Areas of Outstanding Beauty (England)' - see image below.

![image](https://user-images.githubusercontent.com/18594564/28674093-4eab384a-72dc-11e7-8088-996a9a75ec4b.png)

So - it is the 'name' in the 'Add Layer' menu that needs to be changed to match the Description as the two need to match - how can that be done?
Note I have made the same correction to the Welsh layer 'NRW_AONBPolygon'

**Comment by djtfmartin** [comment]
Ive worked out the problem here. It only affects changing the title of the layer.
For notes: The metadata update form updates the "layers" table, but the layer name is actually pulled from the "fields" table in the database which doesnt get the updates to changes to the title (a bug). 
This is easily corrected in the database.



<img width="1440" alt="screenshot 2017-07-27 16 31 21" src="https://user-images.githubusercontent.com/444897/28678772-245a0a3c-72e9-11e7-8500-16dfea2b37d3.png">

**Comment by CEJohnston** [comment]
So just to be clear - if I want to add a country name to a layer name (a few of them need (Scotland) added) is it only you who can do that at the moment?

**Comment by djtfmartin** [comment]
yes that right.
