### ISSUE TITLE
Storm petrel info

### ISSUE THREAD

**Issue by SarahHyslop** [nbnuk/nbnatlas-issues#313]
Feedback from a user;

See https://scotland-species.nbnatlas.org/species/NBNSYS0000000236 The storm petrel info on the site is no use unless you are a French speaker !! Also a picture of the bird would be more useful than a witch on a broomstick!

Could this be rectified? Thanks

**Comment by MandyHenshall** [comment]
This has been raised again today by the same user:
I contacted you several months ago about the content in this page being in French and although there has obviously been something done to the page the text is still in French.
Is there any chance that this can be rectified in the near future so that I can actually make a link to it.

Can we make the necessary changes? Thanks.

**Comment by sophiathirza** [comment]
@reupost would you delete this occurrence record please? https://scotland-records.nbnatlas.org/occurrences/f5b545af-236f-4965-a53d-eaeb22cb6737

thanks.

**Comment by sophiathirza** [comment]
@reupost and this occurrence record too please? https://records.nbnatlas.org/occurrences/d5f94a06-7adc-4701-9414-9a7518edcf4a, thanks.

**Comment by reupost** [comment]
Done
