### ISSUE TITLE
Problems downloading data

### ISSUE THREAD

**Issue by PurbaChoudhury** [nbnuk/nbnatlas-issues#324]
User Stephanie Davies (StephanieDavies@tep.uk.com) has not been able to download some data that she has selected. She is getting the attached error message that her "download is now being queued" but she has not received an E-mail to her account linked to her NBN Atlas account to tell her that the download is complete.  

Is this a new bug? 

Purba

![atlas problem - 11 aug 2017](https://user-images.githubusercontent.com/27347854/29213666-1b798988-7e9c-11e7-8c30-55f856c77a71.JPG)

**Comment by djtfmartin** [comment]
There was a couple problematic downloads that blocked the queue of the weekend. Still investigating the cause, but its now working properly.

Same issue reported here #327 

> She is getting the attached error message that her "download is now being queued" 

This is expected behaviour for all downloads. Downloads are all queued, but there was a problem over the weekend with a couple.
