### ISSUE TITLE
Taxonomic anarchy

### ISSUE THREAD

**Issue by MandyHenshall** [nbnuk/nbnatlas-issues#337]
Sorry, but I can't find my original report of this in the issues list here.  New message on NBN Forum:

>>Please, if I use the search box on the welcome screen, type in "Bombus terrestris" and select "Bombus terrestris - species", why do I see a list of 318 different taxa? 
Why on earth are "Aplanopsis terrestris Höhnk - Taxon group: fungoid, Muriella terrestris J.B. Petersen, 1932 - Taxon group: alga and Microplana terrestris (Müller OF, 1773) - Taxon group: flatworm (Turbellaria)" etc appearing in the list?  I don't want to see every iteration of "terrestris" in the taxon list, I just want the species "Bombus terrestris.
Please get this search function sorted.  Perhaps you could get you developer to look at how it was implemented in the old Gateway - it worked there.

**Comment by djtfmartin** [comment]
I don't think theres an issue here. This is expected behaviour for the system.

The search works by finding the closest match and in the case of "Bombus terrestris" its the top result.

If then will show matches for results which aren't as close to the search term, in this case its matching taxa with the same epithet "terrestris".
