### ISSUE TITLE
Inconsistent naming of species aggregates and s.l. and s.s.

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#426]
Forum post: 

Not sure if this has been raised before (and this specific example may be sorted by changes following a recent Pip post) - records of species aggregates and presumably s.l. and s.s. need to display this in the usual place i.e. following the species name - for instance see the attached. It took a lot of digging on my part to work out this was a record of Pipistrellus pipistrellus agg (or rather the genus, but I won't get into that).

Although I can now see it says "unranked", I didn't when looking down the list and ignored that piece of information. It's also not obvious (again just "unranked") on the actual record page.

Some species appear to be fine e.g. Oulema, Polygonum aviculare agg. - I would suggest doing search for species aggregates that are lacking attributes (agg, s.l. s.s.) in their "display" name.

We have a similar problem in Recorder, where some attributes are part of the name and others are stored separately, so this may be wider species dictionary issue/one for Chris to comment on.

**Comment by sophiathirza** [comment]
Chris has raised the same issue with some other species:

There are two Enicospilus merdarius in UKSI. One had the
https://species.nbnatlas.org/species/NHMSYS0021161445
https://species.nbnatlas.org/species/NBNSYS0000146695

One has a date-restriction qualifier on it, which is not visible on the Atlas

**Comment by sophiathirza** [comment]
Another example is here: https://species.nbnatlas.org/search?fq=idxtype%3ATAXON&q=antherophagus+pallens

The second entry is missing the date qualifier: Antherophagus pallens (Linnaeus, 1758) sensu auctt. ad 2007 non (Linnaeus, 1758)

**Comment by japonicus** [comment]
some plant examples:

_Hedera helix_ **s.l.** https://species.nbnatlas.org/species/NHMSYS0021118909
The taxon page for this labels the rank as 'species sensu lato' but that is easy to overlook. I think the s.l. qualifier needs to be included in the heading.
Occurrence records using this name do not say anywhere that it is the s.l. rather than strict name: e.g.
https://records.nbnatlas.org/occurrences/21782c49-61ab-4a48-9d0e-45aef8520523

_Trichophorum cespitosum_ **s.l.** https://species.nbnatlas.org/species/NHMSYS0021007976
The atlas species page gives no indication that this is the s.l. taxon.
That is only apparent from the details visible in the NHM sandbox:
http://nbn-sd-dev.nhm.ac.uk/taxon.php?linkKey=NHMSYS0021007976

(for comparison the true s.s. name is https://species.nbnatlas.org/species/NHMSYS0021007982 )
There's no way to distinguish the two taxa based on the atlas page.

**Comment by sophiathirza** [comment]
Looking through the UKSI, for some taxons the agg. or s.l./s.s. is part of the taxon name and in other cases they are in the 'Attribute' field of the TAXON_VERSION table.

We are not exporting the Attribute field.

**Comment by sophiathirza** [comment]
Chris has confirmed that we should be using TAXON.ITEM_NAME + TAXON.AUTHORITY + TAXON_VERSION.ATTRIBUTE when we create a taxon name string.

There is no obvious darwin core term for the attribute, nomenclaturalStatus (http://rs.tdwg.org/dwc/terms/#nomenclaturalStatus) looks the best.

**Comment by sophiathirza** [comment]
For the next UKSI update:

use the nameComplete and nameFormatted to build the full names of those taxa that have name attributes.

**Comment by sophiathirza** [comment]
I have added the Attribute field to the taxa table export of the UKSI.

The identificationQualifier DwC term should be used for any name qualifier

**Comment by sophiathirza** [comment]
These have been corrected with the update to the species dictionary. The name attribute is now included, where available.
