### ISSUE TITLE
National Trust for Scotland’s property boundaries

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#434]
Spatial dataset available for upload. Layer name: nts_properties_opendataderived

**Comment by sophiathirza** [comment]
Uploaded but not sampled yet.

**Comment by sophiathirza** [comment]
I've uploaded the layer again (ID: 105). Would you try to sample it please?

**Comment by sophiathirza** [comment]
On deleting a layer, it would be useful to also delete re-projected shape files as the script errors if the short name for the shape file already exists.

**Comment by reupost** [comment]
Hi Sophie

I tested this locally, because I can’t figure out how to sample on the live server without doing everything on a node, which would take ~12hrs.

It seemed fine. There were no errors with the sample-local-node run, and I now have records for cl105 in my database.

I know you were keen to reindex quite soon, would you like to put together a package of things to resolve before then (e.g. the species groups, the issues with those two datasets that didn’t load properly)? I will be available to index as normal at month end, but we could bring it forward a bit if you prefer.

Thanks
Reuben

**Comment by sophiathirza** [comment]
@reupost will this be included in the latest reindexing?

**Comment by sophiathirza** [comment]
NTS boundaries are now available on the spatial portal
