### ISSUE TITLE
Can't go back to search once record is viewed (IOM)

### ISSUE THREAD

**Issue by EllaVogel** [nbnuk/nbnatlas-issues#471]
If you zoom into an area of a map, then click on a point and 'View Record' you see the record (which is great!) but then it would be really nice to go straight back to the zoomed in map you were looking at.

**Comment by EllaVogel** [comment]
Similar issue reported here: In several areas, tabbing backwards takes user back to a default page, not the page in the state the user just left it (e.g. with search results); there is no caching of data, hence you have to restart a search/filtering to get back to where you were

**Comment by reupost** [comment]
Regarding the map, I can't replicate this. If I click on a record point, and then click the browser 'Back' button I return to the map as I left it.  Can you provide more details?  I'm also not quite sure what tabbing backwards involves. Can you give some specific examples?

It might also be worth 'raising' these general Atlas usability issues up from the country-specific Atlases, since they apply across the board.

**Comment by EllaVogel** [comment]
I am able to replicate this. If you search for a species (https://isleofman-records.nbnatlas.org/occurrences/search?q=lsid:NBNSYS0000000013#tab_mapView) and then zoom into a location, say, Peel, then click a point and follow the link through to 'view record', you're taken to a record page. When you then use the back button on the browser, you lose your zoom over Peel and are given a whole Isle of Man view again.

A new issue has come up when looking for this. If you are one grid references on the map, not points, and try to follow through to 'view record', no records are returned!

**Comment by EllaVogel** [comment]
@reupost have you managed to replicate this issue? I need to update the Isle of Man team today on all of their reported issues, so would be good to comment on whether this is fixable in the short term. Cheers.

**Comment by reupost** [comment]
Yes, I could replicate it, thanks :).  The easiest fix would be to open the 'View record' link in a new browser tab, which would leave the map as-is in your existing tab.  This might annoy some users, it's debatable what the expected action would be when you click on the link, whether to open in-place or in a new tab. Alternatively, preserving the map context so that you can go back correctly to the place you were looking when you click 'Back' - that I'd need to investigate a bit more!

**Comment by EllaVogel** [comment]
Thanks. As a short term measure, would it be easy enough to make the records pages open in a new tab automatically, as you've suggested? If this is easy enough to do, it could be worth it (in all Atlases, not just IoM?). Although, I understand if this is too much work for a lower priority task.

**Comment by djtfmartin** [comment]
just my two cents - but automatic opening in a new tab is annoying...

Users can opt to open the link in a new tab already, just with the options in their browser.

**Comment by EllaVogel** [comment]
Yes, I agree to an extent. Ending up with 100 tabs open is annoying, but so is losing your search because you clicked to view the record. If we're not happy to open a new tab automatically, is there a way that we can indicate that to retain the search you need to manually open the link in a new tab?

**Comment by reupost** [comment]
I've added a property to open the map record links in a new tab; if users later decide they don't like this functionality its easy to turn off in the configuration file.  A better long-term fix would be to have the page remember the map zoom and location so that you can return to it in the state you left it.
