### ISSUE TITLE
Correct organism classification on the registry page

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#506]
We need to correct the classification on the registry page (https://registry.nbnatlas.org/).

Fungi are not plants and spiders are not insects: https://forums.nbn.org.uk/viewtopic.php?id=7193

**Comment by CEJohnston** [comment]
@sophiathirza - I have found the file of taxon subgroups that I worked on with @EllaVogel last year - attached below.  Column E contains our suggestion as to the groups to use but we did not complete the file as we got stuck on how to handle the marine items. Ella approached the MBA for help but it is a complex issue for them too and we were not able to pursue it further. I am not sure how far Dave got with implementing our suggestions.  Note this was not a systematic attempt to cover all subgroups - we were just removing references to 'exotic' species not found in the UK.

[NBN Subgroups.xlsx](https://github.com/nbnuk/nbnatlas-issues/files/1954818/NBN.Subgroups.xlsx)

**Comment by sophiathirza** [comment]
I suggest the classification for the registry page should be:

Microorganisms (unchanged)
Plants and bryophytes (remove Fungi)
Invertebrates (rename Insects and include all invertebrates)
Vertebrates (rename Fauna and remove invertebrates)
Fungi (new)

**Comment by CEJohnston** [comment]
This seems like a more consistent high level classification (although I am not an expert taxonomist).  However if it fits logically with the overall UKSI classification structure as well it should be generally accepted by users.

**Comment by reupost** [comment]
Which data partners are listed in each category is controlled by their keywords. We should review these keywords to ensure they match the new categories. At present the keywords which are used are as follows:
fauna             --> Vertebrates
entomology  --> Invertebrates
microbes       --> Microorganisms
plants            --> Plants and bryophytes
fungi              --> Fungi
If any keyword is now particularly inappropriate let me know; otherwise amend the data provider details to ensure they have the required keyword to ensure they appear in the appropriate category

**Comment by reupost** [comment]
I'll deploy the updated version with Fungi and other text changes once I get any revised images to illustrate the groups.

**Comment by reupost** [comment]
Done
