### ISSUE TITLE
Species sub group updates

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#565]
In the regions area several old species groups are still showing:
- [x] remove monocots and dicots
- [x] Algae should be under Plants
- [x] Worms is missing, it should come under Animals
- [ ] Conifers should have Class Pinopsida

**Comment by reupost** [comment]
I think these are all resolved except the additional members of Gymnosperms and Ginkgo (class=Pinopsida) which requires reindexing

**Comment by reupost** [comment]
The regions page is looking a bit the worse for wear, it obviously doesn't like the way we are defining the groups. There are lots of repeats of group 'Plants', e.g. https://regions.nbnatlas.org/National%20parks/BRECON%2520BEACONS%2520NATIONAL%2520PARK#group=ALL_SPECIES&subgroup=&from=1850&to=2018&tab=speciesTab 

I originally though this issue was raised for the 'Explore your area' listing https://records.nbnatlas.org/explore/your-area . I think where possible we should include an example URL demonstrating the issue, to ensure we're all looking at the same problem.

**Comment by reupost** [comment]
Ok, regions page is fixed up
