### ISSUE TITLE
Species group filtering on location search has stopped working

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#611]
Clicking on the different species groups does not filter the list of species when doing a location search: https://records.nbnatlas.org/explore/your-area#51.454513|-2.5879099999999653|12|ALL_SPECIES

Also the number of species in each species group are very similar - I don't think that can be correct.

When viewing the actual records, the species group filters look correct: https://records.nbnatlas.org/occurrences/search?q=*:*&lat=51.454513&lon=-2.5879099999999653&radius=5

**Comment by MandyHenshall** [comment]
Hi, Someone has just called reporting this too.  Any ideas on when the issue will be resolved?
For our area of Nottingham all Species groups show exactly the same number.
Thanks, Mandy

**Comment by reupost** [comment]
This seems to relate to some memory issues on our SOLR database servers, since the way in which the count are calculated are quite processor-intensive. The newer version of our records service component does not trigger the errors and retrieves the counts correctly. This will be deployed as soon as I can resolve some issues with custom downloads that it is struggling with.

**Comment by sophiathirza** [comment]
This is looking much better. It is still running a bit slow and very occasionally the species counts are not correct, but the filtering works and it then possible to view the records for a particular species.

**Comment by sophiathirza** [comment]
This is very much better - thank you. We still have the problem with some of the counts not being correct - but that it a problem with the missing rank ids, which we will correct in the next update of the UKSI.
