### ISSUE TITLE
Vocabulary for identificationVerificationStatus

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#629]
Could we have a fixed vocabulary for identificationVerificationStatus in the same way as we have for basisOfRecord, which maps obvious mistakes to a term and has Unconfirmed as the default?

We have some mistakes creeping in, like Considered Correct rather than Accepted - considered correct. 

Could we also have a record issue when an incorrect identificationVerificationStatus is supplied?

**Comment by sophiathirza** [comment]
Use this dataset for testing: https://registry.nbnatlas.org/public/show/dr1180 as it contains incorrect identificationVerificationStatuses.

Considered Correct mapped to Accepted - considered correct
Correct mapped to Accepted - correct
Unassessed mapped to Unconfirmed - not reviewed

**Comment by reupost** [comment]
Could you advise if there are further mappings to make? At present I have:
Unconfirmed - Unreviewed -> Unconfirmed - Not reviewed
Considered Correct -> Accepted - Considered correct
Correct -> Accepted - Correct
Unassessed -> Unconfirmed - Not reviewed

Some of the other values loaded to date include 'verified', 'occurrence', 'iRecord | Natural England Surveys' (from dr528), quite a few locality names from dr1206, dr1391, etc.

**Comment by sophiathirza** [comment]
The mappings look good except for the capitals:
Unconfirmed - Unreviewed -> Unconfirmed - not reviewed
Considered Correct -> Accepted - considered correct
Correct -> Accepted - correct
Unassessed -> Unconfirmed - not reviewed
Confirmed -> Accepted
Verified  -> Accepted
verified  -> Accepted
Accepted - considered Correct -> Accepted - considered correct

If the value doesn't match, can the processed value be Unconfirmed.

The verification status values in the three datasets that you mention all look okay - where do you see the invalid values? I checked the identificationVerificationStatus facet on the full dataset and didn't see them

**Comment by sophiathirza** [comment]
Looks much better, thanks. There are still a couple that are not correct:
Accepted - considered Correct -> Accepted - considered correct
Correct -> Accepted - considered correct
Confirmed-> Accepted

I'll wait for the next processing run to see if it corrects them.

**Comment by sophiathirza** [comment]
I noticed that this one is wrong (it should be correct not considered correct):
Correct -> Accepted - correct

Could we have some more mappings please?
Not Reviewed -> Unconfirmed - not reviewed
Considered Correct -> Accepted - considered correct

**Comment by reupost** [comment]
Sorry, I'm getting a bit confused. Which one is wrong?

These are the mapping: the item on the left is the submitted term, if there is an item on the right it is the value it is converted to, otherwise the left-hand term is used.

Accepted
Accepted - correct
Accepted - considered correct
Unconfirmed
Unconfirmed - plausible
Unconfirmed - not reviewed
Unconfirmed - unreviewed			Unconfirmed - not reviewed
Considered Correct				Accepted - considered correct
Correct							Accepted - correct
Unassessed						Unconfirmed - not reviewed
Not Reviewed						Unconfirmed - not reviewed

**Comment by sophiathirza** [comment]
this one was wrong in one of my messages above: Correct -> Accepted - considered correct

Your list is perfect - thanks.

**Comment by sophiathirza** [comment]
The verification statuses in this dataset have not picked up the mapping: https://registry.nbnatlas.org/public/show/dr1180

**Comment by reupost** [comment]
I think the mapping has been applied ok at a record-level, e.g: https://records.nbnatlas.org/occurrences/ee166849-edba-4830-8509-8f6e3e6e8d6b and https://records.nbnatlas.org/occurrences/ae01594e-7010-4035-996e-30efaba45780 

It seems the indexing has adopted the supplied identificationverificationstatus rather than the processed version.

**Comment by sophiathirza** [comment]
Looking good now - thanks
