### ISSUE TITLE
Species pages - EoL content - only show the brief summary

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#652]
If possible, please reduce the amount of text displayed on species pages from EoL. Consider only showing the brief summary.

Examples of pages with too much information:
https://wales-species-inns.nbnatlas.org/species/NBNSYS0000002348 , https://scotland-species.nbnatlas.org/species/NBNSYS0000003322 , https://isleofman-species.nbnatlas.org/species/NBNSYS0000011544

**Comment by arbutler90** [comment]
Marsh Fritillary page features both a brief Summary from EoL and full text from EoL:

https://northernireland-species.nbnatlas.org/species/NHMSYS0000516340

**Comment by sophiathirza** [comment]
Can we change the species descriptions from EoL to Wikipedia?

Can all the HTML and headers be removed from the descriptive text, please? This is how map of life does it: e.g. https://mol.org/species/Rubus_idaeus. At the moment there is too much text and the broken HTML looks dreadful.

**Comment by reupost** [comment]
All content is already coming from Wikipedia (via EoL). We've removed non-Wikipedia content unless there isn't a Wikipedia entry. MOL seems to be down right now. Would you mind specifying what content you want (e.g. all paragraphs until the 'Contents' section, or failing that 3 paragraphs, or what-have-you)?

**Comment by sophiathirza** [comment]
MoL is working now.

It is really difficult for me to say without seeing it. In many cases all paragraphs until the Contents section is a lot of text. I would be happy with one paragraph and a link to Wikipedia to read more.

**Comment by reupost** [comment]
Would you mind looking at the Northern Ireland species pages? I've made the following changes:
1. Only one wikipedia article will be shown
2. If there are more than one the first is picked at random (this is often the Brief Summary)
3. Text until the 'Contents' section is included
4. If no Contents section is found, the first three true (non-empty) paragraphs of text are included

If this looks ok, or at least better, I can roll out to other portals. Otherwise let me know further improvements.

**Comment by sophiathirza** [comment]
It looks so much better.

There are still some problems with the HTML, e.g.https://northernireland-species.nbnatlas.org/species/NBNSYS0000000027

Is it possible to strip out the HTML, just leaving the link text as regular text?

**Comment by sophiathirza** [comment]
I will reduce the priority of this for now as it is very much better, unless you want to finish it off.

**Comment by arbutler90** [comment]
The Summary boxes are looking great now. I assume the boxes are just absent entirely if there is no Wiki entry for that species?

**Comment by reupost** [comment]
@arbutler90 yes, unless EoL have other articles. They aggregate content from a range of sources, but we pick out the Wikipedia ones for preference.

**Comment by reupost** [comment]
I've made an attempt to strip out images, since Wikipedia often block external sites from linking directly to their images, but the weird HTML on this page https://northernireland-species.nbnatlas.org/species/NBNSYS0000000027 is actually an artifact of the EoL parsing, it's not something we can easily identify and remove.

I'm going to roll the changes out to other portals and we can review if further issues crop-up.

**Comment by sophiathirza** [comment]
Thanks for this - the species pages are very much better.

If the EoL parsing is causing a problem, could we take the text directly from Wikipedia? And strip out all HTML? Some sections include links saying '[Citation needed]', which would be good to remove. 

I have reduced the priority of this and it is something that we can come back to when we review the species pages.

**Comment by c-van-dierkson** [comment]
Connected to #388?

**Comment by sophiathirza** [comment]
@c-van-dierkson not really. this is about formatting the information that we get from EoL.

**Comment by sophiathirza** [comment]
This can be closed now.
