### ISSUE TITLE
Order existing contacts alphabetically

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#677]
When adding a contact to a data resource or provider could the drop down of existing contacts be in alphabetical order?

Once the list is in order, we can de-duplicate it.

**Comment by reupost** [comment]
At the moment it is in alphabetic order by surname. Which field would you like to use to sort the list?

**Comment by sophiathirza** [comment]
I didn't think that it was ordered at all.. could it be by first name please?

**Comment by reupost** [comment]
The problem is maybe that the text that is shown is not consistently email address or name, so it looks unsorted. At the moment the rule is to show the name (comprising title, firstname, surname) only if a surname is present for the user, otherwise to show email (and if there is no email then it reverts to phone number etc.). We have a fair number of users with their entire name stored in the First name column.

I've changed the rules to use the name if either first or last name are present, and only email address if we have neither.

**Comment by sophiathirza** [comment]
That's so much better - thank you. I plan to de-dup and clean up the list when we roll out editing rights.
