### ISSUE TITLE
Batch species search

### ISSUE THREAD

**Issue by katieoli** [nbnuk/nbnatlas-issues#760]
A user has emailed to point out that this function is not working.  Although this an issue we already know about, I am logging it again and will put it on Trello.

**Comment by sophiathirza** [comment]
I think the reason for this is because it uses the raw_name field rather than the matched or processed scientific name. Most records are supplied with the taxonID and no scientific name.

The query should be changed to query the taxon_name field.

I'll add a card for this on Trello as I couldn't find one.

**Comment by sophiathirza** [comment]
This is now working as expected.
