### ISSUE TITLE
January 2020 spatial layer processing

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#767]
1. LERC boundary update
Layer to be replaced: ID 126
Layer display name: Local Environmental Records Centre Boundaries of the UK
Zip file name: British Isles June 2019 Marine Buffer.zip
Shapefile name: British Isles June 2019 Marine Buffer.shp
Unique ID field: LERC_Short
Name field: LERC_Long
Publication date: 01/06/2019

Warning message:
In readOGR(dsn = ".", layer = "British Isles June 2019 Marine Buffer") :
  Dropping null geometries: 5, 69

LERC boundaries are on the predefined area page:
https://regions.nbnatlas.org/#rt=Local+Environmental+Records+Centres

2. SWT reserve boundaries
Layer to be replaced: ID 113
Layer display name: Scottish Wildlife Trust reserve boundaries
Zip file name: ScottishWildlifeTrust_ReserveBoundaries_20191024.zip
Shapefile name: ScottishWildlifeTrust_ReserveBoundaries_20191024.shp
Unique ID field: OBJECTID
Name field: SITE_NAME
Publication date: 2019-10-24

**Comment by reupost** [comment]
@sophiathirza I removed the two null geometries, but I'm still getting errors. I don't know who provided this shapefile, but if it could be cleaned up it might help. For example:
1. Is there really a tiny exclave of 'Islay Natural History Trust' inside 'Glasgow Museums Biological Records Centre (non-core area)'?
2. Does 'Glasgow Museums Biological Records Centre (non-core area)' have a segment of (self-intersecting) extent north along what is otherwise a boundary between two other LERCs?

I haven't looked in more detail. Point (2) is definitely causing problems with the import.
[gmbrc.zip](https://github.com/nbnuk/nbnatlas-issues/files/4045395/gmbrc.zip)

**Comment by sophiathirza** [comment]
@reupost thanks for letting me know. Leave that one for now and I will investigate with ALERC.

**Comment by reupost** [comment]
![Screenshot 2020-01-10 at 11 49 37](https://user-images.githubusercontent.com/4357196/72151125-5198b380-339f-11ea-8a2d-3f8c8696945a.png)
Another possible issue

**Comment by reupost** [comment]
@sophiathirza the Scottish layer (SWT reserve boundaries) has been added

**Comment by sophiathirza** [comment]
@reupost re: LERC boundary update, apparently it was the wrong version. They've resent the correct one, where the geometries have been checked. It's in Teams. They send their apologies.

**Comment by reupost** [comment]
Ok, that new layer loaded ok. I have added metadata as per the old layers, but please amend as necessary. I will disable the old layers and amend the regions portal to use the new LERC layer once we have rebuild the new index.

**Comment by sophiathirza** [comment]
Thanks. All okay.
